# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CrashDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CrashDemo
  pod 'CrashPreventor', :path => '../'

  target 'CrashDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CrashDemoUITests' do
    # Pods for testing
  end

end
